# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: aubo_arm
  joint_model_group: gripper
  joint_model_group_pose: arm_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.0